### ISSUE TITLE
Baud for the APEX 5000 or 7000

### ISSUE THREAD

**Issue by sagonzal** [PyramidTechnologies/Java-API-Source#7]
I'm  developing a project with a microcontroller and we are willing to include Pyramid Bill acceptors support for our device. I can not use java in it, it has to be in plain C language.

I have a question regarding the serial interface used in APEX 5000 and 7000. In the documents I have it is said to used MARS serial at 600 baud and 8 bit characters. But in another document issued by pyramid (RS_232.pdf ref G) it stated that RS232 must be 7 bit wide and 9600 bauds. Characters of 7 bits are quite uncommon in microcontroller.

What configuration should i use to directly polling the acceptor?

**Comment by ghost** [comment]
MARS 600 and RS-232 are two completely separate protocols. MARS 600 is a very old gaming, two-way asynchronous protocol that is not commonly used on newer equipment. It uses 600 baud and 8 data bits. Probably not what you want to use because it is very insecure.

RS-232 on the other hand is quite robust and uses 9600 baud and 7-bit data length. Depending on your microcontroller, setting the UART to use 7 data bits is as a simple register configuration. All of the microcontrollers in our products support 5-9 data bits on the UART though we use 7-bit for RS-232 because that is what the protocol specifies.

**Comment by sagonzal** [comment]
This is bad news for me. Yes, my micro has a USART that supports 5-9, but I was hoping to use another module that only supports 8 bits. 

APEX 5000 supports MARS...can I send data in that format ? How I know is the bill acceptor I have communicates in MARS or in RS-232.

**Comment by ghost** [comment]
The number of data bits should not affect the logic of your code. Can you
tell me a little more about the problem you are trying to solve? Maybe I
can point you in an easier direction. I do not recommend MARS 600 for new
developments. Use RS-232 or ccTalk for serial communications.

Both 5000 and 7000 support MARS 600. To configure for MARS 600 use Acceptor
Tools or a configuration card.

Acceptor Tools: http://pyramidacceptors.com/apps/acceptorToolsv2/

Configuration Card:
http://pyramidacceptors.com/support/videos/configuration-cards/
Cards available in our manual:
http://www.pyramidacceptors.com/files/Apex_Manual.pdf

On Wed, Sep 2, 2015 at 1:26 PM, sagonzal notifications@github.com wrote:

> This is bad news for me. Yes, my micro has a USART that supports 5-9, but
> I was hoping to use another module that only supports 8 bits.
> 
> APEX 5000 supports MARS...can I send data in that format ? How I know is
> the bill acceptor I have communicates in MARS or in RS-232.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyramidTechnologies/jPyramid-RS-232/issues/7#issuecomment-137233750
> .

## 

Cory Todd
Pyramid Technologies, Inc.
1718 North Quail
Mesa, Arizona 85205

**Comment by ghost** [comment]
We were discussing this internally and think that ccTalk might be a good fit for you since it uses 8-bits of data instead of 7.

**Comment by sagonzal** [comment]
catodd, thank you for your help.  For my tests I have an APEX 5400, connected only with TXD and RXD

It is not clear for me how to manage to use ccTalk and even if I can ise with my test unit. Is it possible ?

**Comment by ghost** [comment]
No problem!

What currency are you looking to accept? Do you have an Apex 7400 available
or only the 5400?

On Thu, Sep 3, 2015 at 8:17 AM, sagonzal notifications@github.com wrote:

> catodd, thank you for your help. For my tests I have an APEX 5400,
> connected only with TXD and RXD
> 
> It is not clear for me how to manage to use ccTalk and even if I can ise
> with my test unit. Is it possible ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyramidTechnologies/jPyramid-RS-232/issues/7#issuecomment-137482414
> .

## 

Cory Todd
Pyramid Technologies, Inc.
1718 North Quail
Mesa, Arizona 85205

**Comment by sagonzal** [comment]
Unlucky, the only gave me an APEX 5400! for testing...it is a dual currency, since the serial end with DOM.

**Comment by ghost** [comment]
Have you download Acceptor Tools? Use Acceptor Tools to find out what
firmware is loaded on the 5400.

On Thu, Sep 3, 2015 at 8:26 AM, sagonzal notifications@github.com wrote:

> Unlucky, the only gave me an APEX 5400! for testing...it is a dual
> currency, since the serial end with DOM.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyramidTechnologies/jPyramid-RS-232/issues/7#issuecomment-137485114
> .

## 

Cory Todd
Pyramid Technologies, Inc.
1718 North Quail
Mesa, Arizona 85205

**Comment by sagonzal** [comment]
OK, but do I need a special cable?

**Comment by ghost** [comment]
Yes, the flash update cable:
http://shop.pyramidacceptors.com/usb-flash-download-cable-for-pc-05aa0026/

The reason I ask is that we no longer develop new firmware for the 5400 so
I highly recommend an Apex 7400.

On Thu, Sep 3, 2015 at 9:40 AM, sagonzal notifications@github.com wrote:

> OK, but do I need a special cable?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyramidTechnologies/jPyramid-RS-232/issues/7#issuecomment-137506454
> .

## 

Cory Todd
Pyramid Technologies, Inc.
1718 North Quail
Mesa, Arizona 85205

**Comment by sagonzal** [comment]
Yes, indeed. What firmware should I download for the 5400 that has ccTalk and has dual currency?

**Comment by ghost** [comment]
Unfortunately we do not support ccTalk on the 5400. I just double checked
and that is an interface we only only support on Apex 7000 and Trilogy.

On Thu, Sep 3, 2015 at 9:58 AM, sagonzal notifications@github.com wrote:

> Yes, indeed. What firmware should I download for the 5400 that has ccTalk
> and has dual currency?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyramidTechnologies/jPyramid-RS-232/issues/7#issuecomment-137511261
> .

## 

Cory Todd
Pyramid Technologies, Inc.
1718 North Quail
Mesa, Arizona 85205

**Comment by sagonzal** [comment]
So, OK, back to base. I configure acceptor for MARS 600 using the  configuration card. Is this OK ? 

I can use TXD and RXD with 600 baud and 8-bit character length. Is this OK ?

**Comment by ghost** [comment]
Yes, that sounds okay to me.

600 BAUD, 8 data bits, 1 start, 1 stop, no parity.

On Thu, Sep 3, 2015 at 10:08 AM, sagonzal notifications@github.com wrote:

> So, OK, back to base. I configure acceptor for MARS 600 using the
> configuration card. Is this OK ?
> 
> I can use TXD and RXD with 600 baud and 8-bit character length. Is this OK
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyramidTechnologies/jPyramid-RS-232/issues/7#issuecomment-137513493
> .

## 

Cory Todd
Pyramid Technologies, Inc.
1718 North Quail
Mesa, Arizona 85205
